### ISSUE TITLE
Request: Port to 1.19.2

### ISSUE THREAD

**Issue by bigfoott** [tweaked-programs/cccbridge#12]
**Description**
Hi! I've looked around and haven't found a statement regarding a possible port to 1.19(.2), so I figured I'd make an issue as a formal request :) It's all good if there aren't any plans or desires to port to 1.19, but I would love to use it if it does get ported :) Thank you!

edit: Just noticed that I left in 1Turtle as the default assignee, sorry about that!

**Comment by SammyForReal** [comment]
Hey,

So currently we have no plans on porting it to the **1.19.2**. My idea is to wait until we release the next major update.

After that, I will probably do a port, but it won't be maintained long, as the **1.20** is already about to get released and others seem to wait for it as the next "maintainer version".

It would be hard for us to update all the versions at once if we add support for every version otherwise.

I know that forge already has Create for **1.19.2**, but fabric is not that far.. So it will be probably only forge for that version too.

Depending on how Create and CC reacts to the **1.20**, we will probably drop support for **1.18.2** more or less too. _(But that is just my claim and still future stuff)_

I hope that satisfies your question. ^^
_-Sammy.K_

**Comment by bigfoott** [comment]
Ah that's understandable. And yeah I'm currently using Create 1.19.2 w/ forge and was looking to add this to a pack I'm playing on with friends at the moment.

No worries though, thanks for the reply! :)
