### ISSUE TITLE
1.19.2 Fabric

### ISSUE THREAD

**Issue by molnarnoah** [tweaked-programs/cccbridge#16]
Hello! Any chance for 1.19.2 Fabric version?

**Comment by Luke1505** [comment]
Yes , we are working on a 1.19.2 but it wont be supported by us as much as the 1.18.2

**Comment by poly2it** [comment]
> it wont be supported by us as much as the 1.18.2  

What does this imply exactly? What are the reasons for this?

**Comment by Luke1505** [comment]
Cause we are focusing on the 1.18.2

**Comment by SammyForReal** [comment]
Hey!
**To make things more clear:** by focusing more on the 1.18.2, we mean that we will develop the next release for the 1.18.2 first. We want to focus on that before chaos begins..

After that, we will start porting to the 1.19.2 and maintain that.

Also: In the past, we weren't sure about maintaining it properly as for example, Create for fabric didnt had anything for the 1.19.2 for months and only maintaining forge or supporting some fork for that version would be weird..

_But now things changed and so our plans._ Just keep in mind that things may take a while. Because we only want to port the next release, so it has to get done first.

I hopy this satisfies the question, I'll let it open until the version is released.

**Comment by SammyForReal** [comment]
Fabric 1.19.2 now available because of: f4b9eca1669eafa4eabe294e6552881bcd911319
Have fun! ^^
