### ISSUE TITLE
Sides of RedRouter

### ISSUE THREAD

**Issue by mymmrac** [tweaked-programs/cccbridge#8]
Hi :wave:, cool mod ))

But I observed that for RedRouter sides seems to be flipped (I would expect them to be relative to player not to face of RedRounter).
Like `right` side will be on the `left` from player's perspective, for me, it's a bit confusing.
What do you think about that?

Also, I would love to have Wiki page for it :)

Thanks for great mod!

**Comment by mymmrac** [comment]
Also, just curious, what is the difference between RedRouter and the already existing Redstone API of CC: T? Maybe there is some plans to add something that can be done by Redstone API?

**Comment by SammyForReal** [comment]
Hey,

the problem with the sides is that CC itself does both.
While Turtles use their sides, Computers use the players sides. I think using the sides from the Turtle is more comfortable, which is why I did it this way. But I will probably also not change it, as this might just destroy already existing code and confuse everyone, which I dont want to happen *(maby with a major update if this should annoy many more people)*.

There shouldnt be any differences between the Redstone API from CC:T and the RedRouter, as it is based on it. ^^

And about the Wiki page, Im working on a script that does that for me, which is why it takes a bit more time *(im nearly done though)*. But if you really need them now, you can look at the javadocs *(Dont worry, you dont have to understand java, just read the docs for the methods that are marked as [AT]LuaFunction)*: [RedRouterBlockPeripheral.java](https://github.com/tweaked-programs/cccbridge/blob/1.18.2-fabric/src/main/java/cc/tweaked_programs/cccbridge/peripherals/RedRouterBlockPeripheral.java#L38)

I hope this was helpfull! ^^

**Comment by mymmrac** [comment]
Yep, understandable), if you will think of RedRouter as a turtle it makes sense to have sides like that.

And for the Wiki, I know Java at some level so this is not a problem for me to read the code) actually, I did that right after creating this issue :sweat_smile: But an auto-generated Wiki page will be cool) 

Thanks)
