### ISSUE TITLE
Create inventories

### ISSUE THREAD

**Issue by mymmrac** [tweaked-programs/cccbridge#9]
As a new feature, it would be cool to be able to interact with Create inventories like belts, depots, item vaults, etc. as with generic inventories.

Maybe as a specific peripheral (also it may be fun if it will require rotational power to work, but it may be hard to implement)

**Comment by Luke1505** [comment]
Yeah i think that should be something that is helpful

**Comment by SammyForReal** [comment]
Yes this indeed would be a nice feature. I was already looking for a way for it, but this wont happen in any time soon, as I have to figure it out by myself too. *(Which doesnt mean others can implement and make a pull request)*

**Comment by Luke1505** [comment]
I've started to look at this point and came to the point that i have started to make plans for various Blocks , what they could do with CC. if you have any idea which block could do what in case of the inventories please let me know 👍🏻 
Kind Regards 
Luke

**Comment by mymmrac** [comment]
Cool) I have some suggestions/ideas. For all things in a list below (I might have missed some, or some can not be easily integrated) there might be some peripheral that works only with rotational power (or no, it depends on how you see it) and interacts with them.

Also, another way is to implement them as `Generic Peripherals` so that computers can work with them directly.

One more thing is upgrade for pocket computers that can be equipped (and also for regular ones) is a `Redstone Link` or `Linked Controller` equipment

Interact as inventory:
- Mechanical Belt
- Blaze Burner
- Mechanical Crafter
- Schematicannon
- Millstone
- Basin
- Portable Storage Interface
- Depot
- Deployer
- Item Vault
- Weighted Ejector

Interact as fluid storage:
- Spout
- Fluid Tank
- Portable Fluid Interface
- Item Drain

Specific interaction:
- Cart Assembler
- Rotation Speed Controller
- Sequenced Gearshift

List of blocks where I searched: https://create.fandom.com/wiki/Category:Blocks

**Comment by WillowMist** [comment]
There is a ton of potential here.  I came here looking for anyone talking about connecting a modem to an item vault.

**Comment by Luke1505** [comment]
Hi, the most of the Basic Create Stuff connection to Computer craft is already beeing handled by the create devs themselves we are only going to edit those if they are not good enough for regular use in CC.

**Comment by WillowMist** [comment]
I worry that Restitched won't get any updates now.   I'm stuck at 1.19.2, since BYG hasn't updated for .3 or .4.  But I'll keep an eye on the main create dev. :)

**Comment by SammyForReal** [comment]
Some time has passed by now. And within that Create now introduced their own peripherals for some stuff like fluid storage.
As for the inventory problem here, we wont fix that. Turns out this is a general problem with Fabric inventories. Those don't get recognized in CC:R. Implementing this would be too much effort.

Within the [Port to 1.20](https://github.com/tweaked-programs/cccbridge/issues/48) , this will be fixed however due to the switch to the including [Switch from CC:R to CC:T in Fabric](https://github.com/tweaked-programs/cccbridge/issues/24) .

As an alternative for the versions that still use CC:R, the fabric mod [UnlimitedPeripheralWorks](https://github.com/SirEdvin/UnlimitedPeripheralWorks) solves exactly this problem.
